#!/bin/env zsh

[[ -f $_dot_bootstrap_root_/generated/failure_hash ]] || return
current_hash="$( source $_dot_bootstrap_root_/runtime/generator/check_last_generation_failure_status )"
failure_hash="$( head -n1 $_dot_bootstrap_root_/generated/failure_hash )"
[[ "$current_hash" == "$failure_hash" ]] && {
  echo "[fingerprint/module/check_last_generation_failure_status] this snapshot has already failed previously : $( head -n1 $_dot_bootstrap_root_/generated/failure_hash )" | error
  echo "[fingerprint/module/check_last_generation_failure_status] failure_hash : $failure_hash " | error
  echo "[fingerprint/module/check_last_generation_failure_status] current_Hash : $current_hash " | error
  generation_error="[fingerprint/module/check_last_generation_failure_status] this snapshot has already failed previously"
}

