#!/bin/env zsh

[[ -d $_dot_bootstrap_root_/generated ]] || { mkdir $_dot_bootstrap_root_/generated }
[[ -f $_dot_bootstrap_root_/generated/cwd ]] || { echo "$_dot_bootstrap_root_" > $_dot_bootstrap_root_/generated/cwd  }
