#!/bin/env zsh

[[ -f $_dot_bootstrap_root_/cache/init ]] || {
  echo "[fingerprint/module/hash_module] cache/init not found invoking module generator" | warn
  source $_dot_bootstrap_root_/runtime/generator/module
  state="${state}hash_module "
  return
}

local activeSource="$(dirname -- $( grep "source" $_dot_bootstrap_root_/cache/init | sed -e 's/^ *source *//g' ))"

[[ -f "$activeSource/module" ]] || {
  echo "[fingerprint/module/hash_module] cache/\$activeSource/module not found invoking module generator" | warn
  source $_dot_bootstrap_root_/runtime/generator/module
  state="${state}hash_module "
  return
}

[[ -f "$_dot_bootstrap_root_/config/module" ]] || {
  echo "[fingerprint/module/hash_module] config/module not found invoking module generator" | warn
  source $_dot_bootstrap_root_/runtime/generator/module
  state="${state}hash_module "
  return
}

if [[ "$( sort $_dot_bootstrap_root_/config/module)" == "$(cat $activeSource/module )" ]]; then
  echo "[fingerprint/module/hash_module] config/module unchanged no action required" | debug
else
  echo "[fingerprint/module/hash_module] config/module hash been modified invoking module generator" | warn
  source $_dot_bootstrap_root_/runtime/generator/module
  state="${state}hash_module "
fi
