#!/bin/env zsh

[[ -f "$_dot_bootstrap_root_/config/module" ]] || {
  echo "[fingerprint/module/module] config/module not found generatorating an empty file" | warn
  touch "$_dot_bootstrap_root_/config/module" 
}

[[ -f $_dot_bootstrap_root_/generated/init ]] || {
  echo "[fingerprint/module/module] generated/init not found invoking module generator" | warn
  source $_dot_bootstrap_root_/runtime/generator/module
  state="${state}module "
  return
}

local activeSource="$(dirname -- $( grep "source" $_dot_bootstrap_root_/generated/init | sed -e 's/^ *source *//g' ))"

[[ -f "$activeSource/module" ]] || {
  echo "[fingerprint/module/module] generated/\$activeSource/module not found invoking module generator" | warn
  source $_dot_bootstrap_root_/runtime/generator/module
  state="${state}module "
  return
}

if [[ "$( sort $_dot_bootstrap_root_/config/module)" == "$(awk -F ':' '{ print $1 }' $activeSource/module )" ]]; then
  echo "[fingerprint/module/module] config/module unchanged no action required" | debug
else
  echo "[fingerprint/module/module] config/module hash been modified invoking module generator" | warn
  source $_dot_bootstrap_root_/runtime/generator/module
  state="${state}module "
fi
