#!/bin/env zsh

# @f->ALLOW_EXPLICIT_ASCII
# @e->ASCII_SEARCH_QUERY
# @e->ASCII_DIMENSION_HEIGHT
# @e->ASCII_DIMENSION_WIDTH
# @e->ASCII_DIMENSION_HEIGHT_MIN
# @e->ASCII_DIMENSION_WIDTH_MIN
# @d->env_flags
# @f->USE_RAM_FOR_ASCII_ART_FASTFETCH
# @nolazy

[[ -v "ASCII_SEARCH_QUERY" ]] || {
  echo "ASCII_SEARCH_QUERY Not found"
  echo "export ASCII_SEARCH_QUERY=\".*\""
  return
}

[[ "$ASCII_SEARCH_QUERY" != *[!$' \t\r\n']* ]] && {
  echo "ASCII_SEARCH_QUERY is blank"
  echo "export ASCII_SEARCH_QUERY=\".*\""
  return
}

_get_encoded_url() {
  url="https://emojicombos.com/api/search?keyphrase=$escaped_search_query"
  wget "$url" -qO - | sed -e 's#https://emojicombos.com/##g'
}

_download_ascii_art() {
  [[ -f "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/cached_query" ]] || touch "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/cached_query"
  cached_query="$( grep -F "$escaped_search_query:" "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/cached_query" | tail -n1 )"
  if [[ -z "$cached_query" ]] ; then
    echo "cached query : false"
    encoded="$(_get_encoded_url)"
    echo "$escaped_search_query:$encoded" >> "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/cached_query"
  else
    echo "cached query : true"
    encoded="$( cut -d ':' -f2 <<< "$cached_query" )"
  fi
  url="https://emojicombos.com/$encoded"
  if [[ -v USE_RAM_FOR_ASCII_ART_FASTFETCH ]] ; then
    local path_dev_shm_prefix="/dev/shm/ascii_art_fastfetch_$(uuidgen)"
  [[ -d "$path_dev_shm_prefix" ]] || mkdir -p "$path_dev_shm_prefix"
    html="$path_dev_shm_prefix/$encoded.html"
    inversionMap="$path_dev_shm_prefix/inversionMap.py"
  else
    html="$_dot_bootstrap_root_/generated/ascii_art_fastfetch/$encoded.html"
    inversionMap="$_dot_bootstrap_root_/generated/ascii_art_fastfetch/inversionMap.py"
  fi
  echo "search       : https://emojicombos.com/api/search?keyphrase=$encoded"
  echo "encoded      : ${encoded/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}"
  [[ "$encoded" == "https://emojidb.org/"* ]] && {
    _ascii_art_fastfetch_error_="No webpage found for this query : \"$ASCII_SEARCH_QUERY\""
    echo "$escaped_search_query:" >> "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries"
    return
  }
  echo "url          : $url"
  echo "html         : ${html/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}"
  echo "output       : ${output/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}"
  echo "explicit     : $( if [[ -v "ALLOW_EXPLICIT_ASCII" ]] ; then echo true ; else echo false ; fi )"
  echo "inversionMap : ${inversionMap/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}"
  [[ -d "$output.temp" ]] || mkdir -p "$output.temp"
  [[ -f "$html" ]] || wget "$url" -O "$html"
  [[ -f "$html.trimmed" ]] || sed -e 's#^[[:space:]]\+\(<[[:space:]]*div\)#\1#g' "$html" > "$html.trimmed"
  [[ -f "$inversionMap" ]] || {
    print -n -- "\r-> generating inversionMap"
    print -- "#!/bin/env python" > "$inversionMap"
    print -- "import sys" >> "$inversionMap"
    grep -Po "dotArtInversionMap *= *.*" "$html" | sed -e 's#;##g' >> "$inversionMap"
    print -- "with open(sys.argv[1]) as file:" >> "$inversionMap"
    print -- "    for line in file:" >> "$inversionMap"
    print -- "        for char in line.rstrip('\\\n'):" >> "$inversionMap"
    print -- "            if char in dotArtInversionMap:" >> "$inversionMap"
    print -- "                print(dotArtInversionMap[char],end=\"\")" >> "$inversionMap"
    print -- "            else:" >> "$inversionMap"
    print -- "                print(char)" >> "$inversionMap"
    print -- "        print()" >> "$inversionMap"
    chmod +x "$inversionMap"
    print -n -- "\r-> generated inversionMap     \n"
  }

  elements=$(htmlq '.emoji-wrap' < "$html.trimmed" )
  
  count=$(grep -Po '(?<=class=)"[^"]*emoji-wrap[^"]*"' "$html" | wc -l)
  
  saved=0
  inverted_count=0

  for ((i = 0; i < count; i++)); do
 
    adult_art_encoded_data=$( print -r -- "$elements" | htmlq -a data-encoded-text ".emoji-wrap:nth-child($((i + 1))) .emojis")
    data_type=$( print -r -- "$elements" | htmlq -a data-type ".emoji-wrap:nth-child($((i + 1))) .emojis")

    # Skip sensitive/explicit entries unless ALLOW_EXPLICIT_ASCII is set.
    [[ ! -v "ALLOW_EXPLICIT_ASCII" ]] && [[ ! -z "$adult_art_encoded_data" ]] && {
        print -n -- "\r-> extracting $((i + 1))/$count"
        continue
    }

    if [[ -z "$adult_art_encoded_data" ]] ; then
      normal_art=$( print -r -- "$elements" | htmlq -t ".emoji-wrap:nth-child($((i + 1))) ")
      print -r -- "$normal_art" > "$output.temp/$saved.ascii"
      output_art_file="$output.temp/$saved.ascii"
      [[ "$data_type" == "dot_art" ]] && echo "$data_type" > "$output.temp/${saved}.ascii.inverted"
    else 
      print -r -- "$adult_art_encoded_data" | base64 -d > "$output.temp/${saved}_explicit.ascii"
      output_art_file="$output.temp/${saved}_explicit.ascii"
      [[ "$data_type" == "dot_art" ]] && echo "$data_type" > "$output.temp/${saved}_explicit.ascii.inverted"
    fi
  
    [[ "$data_type" == "dot_art" ]] && ((inverted_count++))
    ((saved++))

    print -n -- "\r-> extracting $((i + 1))/$count"
  done

  print -- "\r-> extracted $saved/$count  "

  while IFS= read -r file ; do
    print -n -- "\r-> inverting : $file                             "
    "$inversionMap" "$output.temp/$file" > "$output.temp/$file.inverted"
  done <<(ls "$output.temp" | grep -Po ".*(?=\.inverted)" )

  [[ -v USE_RAM_FOR_ASCII_ART_FASTFETCH ]] && rm -r "$path_dev_shm_prefix"
  unset path_dev_shm_prefix

  print -- "\r-> inverted $inverted_count/$count                   "
  print -- "\r-> saved $(($inverted_count+$saved))                   "
  mv "$output.temp" "$output"

}

_ascii_art_refresh_() {
  [[ -d "$_dot_bootstrap_root_/generated/ascii_art_fastfetch" ]] || mkdir -p "$_dot_bootstrap_root_/generated/ascii_art_fastfetch"
  unset _ascii_art_fastfetch_error_
  escaped_search_query=$(jq -rn --arg v "$ASCII_SEARCH_QUERY" '$v|@uri')
  output="$_dot_bootstrap_root_/generated/ascii_art_fastfetch/$escaped_search_query"
  [[ -v "ALLOW_EXPLICIT_ASCII" ]] && output="${output}_explicit"
  [[ -f "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries" ]] || touch "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries"
  
  grep -q "^$escaped_search_query:" "$_dot_bootstrap_root_/generated/ascii_art_fastfetch/failed_queries" && {
    _ascii_art_fastfetch_error_="This query had no result : \"$ASCII_SEARCH_QUERY\""
    return
  
  }
  [[ -d "$output" ]] || _download_ascii_art
  [[ -v _ascii_art_fastfetch_error_ ]] && return
  
  _ascii_art_dir_="$output"

  if [[ "$ASCII_DIMENSION_HEIGHT_MIN" == *[!$' \t\r\n']* ]] && [[ "$ASCII_DIMENSION_WIDTH_MIN" == *[!$' \t\r\n']* ]] ; then
    local dimension_output="${_ascii_art_dir_}_min_${ASCII_DIMENSION_HEIGHT_MIN}x${ASCII_DIMENSION_WIDTH_MIN}"
    [[ -d "$dimension_output" ]] || {
      echo "filtering min  : ${ASCII_DIMENSION_HEIGHT_MIN}x${ASCII_DIMENSION_WIDTH_MIN}"
      mkdir -p "$dimension_output.temp"
      local saved=0
      local total="$( ls "$output" | wc -l | cut -d ' ' -f1 )"
      find "$_ascii_art_dir_" -maxdepth 1 -type f -print0 | xargs -0 -n1 sh -c 'wc -l "$1" | cut -d " " -f1 | tr "\n" ":" ; awk "length > max { max = length } END { print max }" "$1" | tr "\n" ":" ; echo "$1"' _ | tr '\n' '\0' | xargs -0 -n1 sh -c 'dimension=() ; dimension[0]="$(echo "$1" | cut -d ':' -f1 )"; dimension[1]="$(echo "$1" | cut -d ':' -f2 )" ;  dimension[2]="$(echo "$1" | cut -d ':' -f3 )" ; if (( "${dimension[0]}" >= ASCII_DIMENSION_HEIGHT_MIN )) && (( "${dimension[1]}" >= ASCII_DIMENSION_WIDTH_MIN )) ; then echo "${dimension[2]}" ; fi' _ | while IFS= read -r file; do
        file_name="${file##*/}"
        print -n -- "\r-> copying $file_name                          "
        cp "$file" "$dimension_output.temp/$file_name"
        ((saved++))
      done
      print -- "\rfiltered   : $saved/$total                        "
      mv "$dimension_output.temp" "$dimension_output"
    }
    _ascii_art_dir_="$dimension_output"
  fi

  if [[ "$ASCII_DIMENSION_HEIGHT" == *[!$' \t\r\n']* ]] && [[ "$ASCII_DIMENSION_WIDTH" == *[!$' \t\r\n']* ]] ; then
    local dimension_output="${_ascii_art_dir_}_max_${ASCII_DIMENSION_HEIGHT}x${ASCII_DIMENSION_WIDTH}"
    [[ -d "$dimension_output" ]] || {
      echo "filtering max  : ${ASCII_DIMENSION_HEIGHT}x${ASCII_DIMENSION_WIDTH}"
      mkdir -p "$dimension_output.temp"
      local saved=0
      local total="$( ls "$_ascii_art_dir_" | wc -l | cut -d ' ' -f1 )"
      find "$_ascii_art_dir_" -maxdepth 1 -type f -print0 | xargs -0 -n1 sh -c 'wc -l "$1" | cut -d " " -f1 | tr "\n" ":" ; awk "length > max { max = length } END { print max }" "$1" | tr "\n" ":" ; echo "$1"' _ | tr '\n' '\0' | xargs -0 -n1 sh -c 'dimension=() ; dimension[0]="$(echo "$1" | cut -d ':' -f1 )"; dimension[1]="$(echo "$1" | cut -d ':' -f2 )" ;  dimension[2]="$(echo "$1" | cut -d ':' -f3 )" ; if (( "${dimension[0]}" <= ASCII_DIMENSION_HEIGHT )) && (( "${dimension[1]}" <= ASCII_DIMENSION_WIDTH )) ; then echo "${dimension[2]}" ; fi' _ | while IFS= read -r file; do
        file_name="${file##*/}"
        print -n -- "\r-> copying $file_name                          "
        cp "$file" "$dimension_output.temp/$file_name"
        ((saved++))
      done
      print -- "\rfiltered   : $saved/$total                          "
      mv "$dimension_output.temp" "$dimension_output"
    }
    _ascii_art_dir_="$dimension_output"
  fi

}

:ascii-art-refresh() {
  _ascii_art_refresh_
}

:ascii-art-fastfetch() {
  [[ -v _ascii_art_fastfetch_error_ ]] && {
    echo "$_ascii_art_fastfetch_error_ "
    echo "change query then \":ascii-art-refresh && :ascii-art-fastfetch\""
    return
  }
  local random_art="$(ls "$_ascii_art_dir_" | shuf -n 1)"
  echo "[modules/ascii-art-fastfetch] using dir : \"$_ascii_art_dir_\"" | debug
  echo "[modules/ascii-art-fastfetch] using art : \"$random_art\"" | debug
  cat "$_ascii_art_dir_/$random_art" | fastfetch --file -
}

_ascii_art_refresh_
:ascii-art-fastfetch
