#!/bin/env zsh

# @e->EDITOR

_inline_buffer_editor() {
  local inline_buffer="/dev/shm/inline_zsh_buffer_$(uuidgen)"
  echo "$BUFFER" > "$inline_buffer"
  if (( $+functions[popup_editor_tmux] )); then
    popup_editor_tmux "$inline_buffer" 2>/dev/null >/dev/null
    (( "$?" )) && {
      "$EDITOR" "$inline_buffer"
    }

  else
    "$EDITOR" "$inline_buffer"
  fi
  BUFFER=$( cat "$inline_buffer" )
  CURSOR=${#BUFFER}
  rm "$inline_buffer"
}

zle -N _inline_buffer_editor
bindkey '^E' _inline_buffer_editor
