#!/bin/zsh

[[ -d "$_zforge_root_/local/public/config/loadBin" ]] || {
  mkdir -p "$_zforge_root_/local/public/config/loadBin"
  echo \[loadBin\] created path | debug
}

export PATH="$PATH:$_zforge_root_/local/public/config/loadBin"
echo \[loadBin\] loaded path "$_zforge_root_/local/public/config/loadBin" | debug

[[ -d "$_zforge_root_/local/private/config/loadBin" ]] || {
  mkdir -p "$_zforge_root_/local/private/config/loadBin"
  echo \[loadBin\] created path | debug
}

export PATH="$PATH:$_zforge_root_/local/private/config/loadBin"
echo \[loadBin\] loaded path "$_zforge_root_/local/private/config/loadBin" | debug
