#!/bin/zsh

# @p-> 1002
# @f-> USE_RAM_FOR_TEMP_ALIAS_FILE

if [[ -f $_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES  ]] ; then 
  source $_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES
  echo \[persistentAlias\] sourced STORED_ALIASES config file  | debug
else
  echo \[persistentAlias\] no aliases found : STORED_ALIASES config file missing | warn
  mkdir -p $_dot_bootstrap_root_/config/public/persistentAlias/
  touch $_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES
  echo \[persistentAlias\] created STORED_ALIASES config file  | warn
fi

unalias() {
  local delete=false 
  if [[ "$1" == "--delete" ]] ; then 
    shift
    echo "[persistentAlias] delete arg found $@" | debug
    delete=true 
  fi
  local newAliasTempFile="$_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES_NEW"
  if [[ -v USE_RAM_FOR_TEMP_ALIAS_FILE ]] ; then
    newAliasTempFile="/dev/shm/persistentAlias/STORED_ALIASES_NEW"
  fi
  if [[ ! -d ${newAliasTempFile%/*} ]] ; then 
    mkdir -p ${newAliasTempFile%/*}
  fi
  for arg in "$@"; do
    builtin unalias $arg 
    local didItWorked=$?
    if [[ "$delete" == "false" ]] ; then 
      echo "[persistentAlias] delete not found for this $arg" | debug
      continue
    fi
    if [[ $didItWorked > 0 ]] ; then 
      echo \[persistentAlias\] "failed to unalias $arg" | error
      continue
    fi
    touch $newAliasTempFile
    local name=$arg
    local ignore=false
    local oldAlias=""
    while read -r line ; do 
      if [[ $( echo $line | awk '{ print $1 }'  ) == 'builtin' ]] ; then
        if [[ $ignore == true ]] ; then 
          ignore=false
        fi
        local iteratedAliasName="$(echo $line | awk '{ print $3 }' | awk -F '=' '{print $1}')"
        if [[ $iteratedAliasName == $name ]] ; then 
          ignore=true
        fi
      fi
      if [[ $ignore == true ]]; then
        oldAlias="$oldAlias\n$line"
      else
        echo $line >> $newAliasTempFile
      fi
    done < $_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES
    mv $newAliasTempFile $_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES
    if [[ ! -z $oldAlias ]] ; then 
      echo \[persistentAlias\] "deleted alias $oldAlias" | debug
    fi
  done
}

alias() {
  local save=false
  if [[ $1 == "--save" ]] ; then 
    shift
    echo "[persistentAlias] save arg found $@" | debug
    save=true
  fi
  builtin alias "$@"
  local exitCode=$?
  if [[ $save == "false" ]] ; then 
    echo "[persistentAlias] save arg not found for $@" | debug
    return
  fi
  if [[ $exitCode > 0 ]] ; then
    echo \[persistentAlias\] return $exitCode for alias \"$@\" | error
    return
  fi

  local newAliasTempFile="$_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES_NEW"
  
  if [[ -v USE_RAM_FOR_TEMP_ALIAS_FILE ]] ; then
    newAliasTempFile="/dev/shm/persistentAlias/STORED_ALIASES_NEW"
  fi

  if [[ ! -d ${newAliasTempFile%/*} ]] ; then 
    mkdir -p ${newAliasTempFile%/*}
  fi

  for arg in "$@"; do
    if [[ -f $newAliasTempFile ]] ; then 
      rm $newAliasTempFile
    fi
    touch $newAliasTempFile
    print -r -- "builtin alias ${(q)arg}" > $newAliasTempFile 
    source $newAliasTempFile >/dev/null 2>&1
    local drySource=$?
    if [[ $drySource > 0 ]] ; then 
      echo \[persistentAlias\] "the alias correct but failed when written to file code : \"$drySource\" alias: \"$@\"" | error
      continue
    fi
    rm $newAliasTempFile
    touch $newAliasTempFile
    local name=$(echo $arg | awk -F '=' '{ print $1 }' )
    local ignore=false
    local oldAlias=""
    while read -r line ; do 
      if [[ $( echo $line | awk '{ print $1 }'  ) == 'builtin' ]] ; then
        if [[ $ignore == true ]] ; then 
          ignore=false
        fi
        local iteratedAliasName="$(echo $line | awk '{ print $3 }' | awk -F '=' '{print $1}')"
        if [[ $iteratedAliasName == $name ]] ; then 
          ignore=true
        fi
      fi
      if [[ $ignore == true ]]; then
        oldAlias="$oldAlias\n$line"
      else
        echo $line >> $newAliasTempFile
      fi
    done < $_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES
    print -r -- "builtin alias ${(q)arg}" >> $newAliasTempFile
    mv $newAliasTempFile $_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES
    if [[ -z $oldAlias ]] ; then 
      echo \[persistentAlias\] "added new alias builtin alias ${(q)arg}" | debug
    else
      echo \[persistentAlias\] "replaced old alias $oldAlias" | debug
    fi
  done
}

:listAliases() {
  local selected alias_name

  selected=$(
    grep "alias \+[^=]\+" "$_dot_bootstrap_root_/config/public/persistentAlias/STORED_ALIASES" |
    fzf \
      --preview-window=wrap \
      --preview 'echo {} | bat --decorations=never --language=zsh --color=always'
  )

  [[ -z $selected ]] && return
  
  alias_name=${selected#builtin }
  alias_name=${alias_name#alias }
  alias_name=${alias_name%%=*}

  print -z $alias_name 

}
