#!/bin/zsh

if [[ ! -d $HOME/.sdkman ]]; then 
  curl -s "https://get.sdkman.io" | bash
fi

export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
