#!/bin/zsh

_dot_flag_enable() {
  $_dot_bootstrap_root_/runtime/logger debug "Enable Flag : $1"
  echo "$1" >> $_dot_bootstrap_root_/config/FLAGS
  export $1=1
}

_dot_flag_disable() {
  $_dot_bootstrap_root_/runtime/logger debug "Disable Flag : $1"
  if [[ -f $_dot_bootstrap_root_/config/FLAGS_$1 ]] ; then
    rm $_dot_bootstrap_root_/config/FLAGS_$1
  fi
  touch $_dot_bootstrap_root_/config/FLAGS_$1
  while read -r line; do
    if [[ $line != $1 ]] ; then
      echo "$line" >> $_dot_bootstrap_root_/config/FLAGS_$1
    fi
  done < $_dot_bootstrap_root_/config/FLAGS
  mv $_dot_bootstrap_root_/config/FLAGS_$1 $_dot_bootstrap_root_/config/FLAGS
  unset $1
}

:listFlags() {
  local RED="\e[1;31m"
  local GREEN=$'\e[1;32m'
  local RESET="\e[0m"
  local TICK="✓"
  local CROSS="✗"
  local output="$(while read -r line ; do 
    if [[ "$(grep -o "$line" $_dot_bootstrap_root_/config/FLAGS)" == $line ]] ; then
      printf "${GREEN}${TICK}${RESET} "
    else
      printf "${RED}${CROSS}${RESET} "
    fi
    echo "$line"
  done < $_dot_bootstrap_root_/runtime/LIST_OF_FLAGS )" 
  for line in $( echo $_dot_dynamic_flags | tr '\n' ' ') ; do
    if [[ -z $line ]] ; then
      continue
    fi
    output+="\n$(if [[ "$(grep -o "$line" $_dot_bootstrap_root_/config/FLAGS)" == $line ]] ; then
      printf "${GREEN}${TICK}${RESET} "
    else
      printf "${RED}${CROSS}${RESET} "
    fi
    echo "$line")"
  done

  if [[ -v DISABLE_DOT_LIST_PAGER ]] ; then
    echo $output
  else 
    echo $output | less 
  fi
}

:flag() {
  local RED="\e[1;31m"
  local RESET="\e[0m"
  local CROSS="✗"
  DISABLE_DOT_LIST_PAGER=1
  while true ; do
    local output="$( :listFlags | {cat; echo "${RED}quit${RESET}" ;} | fzf --ansi)"
    if [[ $output == "" ]] || [[ $output == "quit" ]] ; then
      return
    fi
    if [[ "$(echo $output| awk '{ print $1 }')" == $CROSS ]] ; then
      _dot_flag_enable "$(echo $output | awk '{ print $2 }')"
    else
      _dot_flag_disable "$(echo $output | awk '{ print $2 }')"
    fi
  done
  unset DISABLE_DOT_LIST_PAGER
}
