#!/bin/zsh

:list_module() {
  local RED="\e[1;31m"
  local GREEN=$'\e[1;32m'
  local RESET="\e[0m"
  local TICK="✓"
  local CROSS="✗"

  local output="$(find "$_zforge_root_/modules" -type f | \
  while read -r line; do
    if [[ "$(  head -n1 "$line" | grep -o '^#!\(/usr\)\?/bin/\(env \)\?zsh' )" == "" ]] ; then
      continue
    fi
    line=${line#"$_zforge_root_/modules/"}
    if [[ "$(grep -o "^$line\$" "$_zforge_root_/local/public/runtime/module")" == "$line" ]] ; then
      printf "${GREEN}${TICK}${RESET} "
    else
      printf "${RED}${CROSS}${RESET} "
    fi
    echo "$line"
  done)"

  if [[ -v DISABLE_DOT_LIST_PAGER ]] ; then
    echo $output
  else 
    echo $output | less 
  fi
}

_dot_module_enable() {
  echo "Enable module : $1" | debug
  echo "$1" >> "$_zforge_root_/local/public/runtime/module"
  # source "$_zforge_root_/modules/$1"
}

_dot_module_disable() {
  suffix="$( echo $1 | sed -e "s/\//#/g" )"
  echo "Disable module : $1" | debug
  if [[ -f "$_zforge_root_/local/public/runtime/module_$suffix" ]] ; then
    rm "$_zforge_root_/local/public/runtime/module_$suffix"
  fi
  touch "$_zforge_root_/local/public/runtime/module_$suffix"
  while read -r line; do
    if [[ $line != $1 ]] ; then
      echo "$line" >> "$_zforge_root_/local/public/runtime/module_$suffix"
    fi
  done < "$_zforge_root_/local/public/runtime/module"
  mv "$_zforge_root_/local/public/runtime/module_$suffix" "$_zforge_root_/local/public/runtime/module"
  echo "Shell Retart is required to apply changed" | debug
}

:module() {
  local RED="\e[1;31m"
  local RESET="\e[0m"
  local CROSS="✗"
  DISABLE_DOT_LIST_PAGER=1
  while true ; do
    local output="$( :list_module | {cat; echo "${RED}quit${RESET}";} | fzf --ansi)"
    if [[ $output == "" ]] || [[ "$output" == "quit" ]] ; then
      break 
    fi
    if [[ "$(echo $output| awk '{ print $1 }')" == $CROSS ]] ; then
      _dot_module_enable "$(echo $output | awk '{ print $2 }')"
    else
      _dot_module_disable "$(echo $output | awk '{ print $2 }')"
    fi
  done
  [[ -v INSTANT_REGENERATION ]] && {
    if [[ "$*" == *"--silent"* ]] ; then
      zforge --generate --silent
    elif [[ "$*" == *"--page"* ]]; then
      zforge --generate | less
    else
      zforge --generate
    fi
  }
  unset DISABLE_DOT_LIST_PAGER
}
