#!/bin/env zsh

zmodload zsh/datetime
local _init_start=$EPOCHREALTIME

source "$(dirname -- $(realpath ${(%):-%N}))/initialize/env"
source "$_zforge_root_/runtime/initialize/init_logger"
source "$_zforge_root_/runtime/initialize/first_boot_optimisation"

[[ -v _zforge_bootstrap_error_ ]] && {
  [[ "$ZSH_EVAL_CONTEXT" == "toplevel" ]] && exit
  return
}

echo "root dir : $_zforge_root_" | debug
echo "session id : $_session_id_" | debug

# running as script
[[ "$ZSH_EVAL_CONTEXT" == "toplevel" ]] && {
  source "$_zforge_root_/runtime/initialize/init_being_run" "$@"
  exit
}

builtin alias zforge="$_zforge_root_/runtime/init"

source "$_zforge_root_/runtime/orchestrator/main"

source "$_zforge_root_/runtime/loaders/load_shell_api"

if [[ -f "$_zforge_root_/cache/generated/runtime/init" ]]; then
   source "$_zforge_root_/cache/generated/runtime/init"
else
  echo "[init] generated/init not found" | error
fi

local _init_end=$EPOCHREALTIME
printf '[init] foreground time %.3f ms\n' "$(( (_init_end - _init_start) * 1000 ))" | debug
