#!/bin/env zsh

zmodload zsh/datetime
local _init_start=$EPOCHREALTIME

source $(dirname -- $(realpath ${(%):-%N}))/initialize/env 
source $_dot_bootstrap_root_/runtime/initialize/init_logger

echo "root dir : $_dot_bootstrap_root_" | debug
echo "session id : $_session_id_" | debug
echo "$_session_id_" 

source $_dot_bootstrap_root_/runtime/fingerprint/main

source $_dot_bootstrap_root_/runtime/loaders/load_shell_api
 
if [[ -f "$_dot_bootstrap_root_/generated/init" ]]; then
   #source "$_dot_bootstrap_root_/generated/init"
else
  echo "[init] generated/init not found" | error
fi

local _init_end=$EPOCHREALTIME
printf '[init] foreground time %.3f ms\n' "$(( (_init_end - _init_start) * 1000 ))" | debug


if [[ $1 == "--log" ]]; then
  :log
fi
