#!/bin/env zsh

if [[ ! -f $_dot_bootstrap_root_/cache/cwd ]] ; then
  echo "[fingerprint/cwd_change] cache/cwd file not found" | error
  echo "[fingerprint/cwd_change] cache/cwd file not found"
  [[ ! -d $_dot_bootstrap_root_/cache ]] || rm -r $_dot_bootstrap_root_/cache
  state="${state}cwd_change "
  return
fi

local _root_cwd="$(cat $_dot_bootstrap_root_/cache/cwd)"
if [[ $_root_cwd != "$_dot_bootstrap_root_" ]] ; then
  echo "[fingerprint/cwd_change] dotfile directory moved from $_root_cwd to $_dot_bootstrap_root_" | warn
  echo "[fingerprint/cwd_change] dotfile directory moved from $_root_cwd to $_dot_bootstrap_root_"
  echo "[fingerprint/cwd_change] force forground generation required "
  [[ ! -d $_dot_bootstrap_root_/cache ]] || rm -r $_dot_bootstrap_root_/cache
  state="${state}cwd_change "
fi
