#!/bin/env zsh

local generation_error=""

modules_arr=(
  $_dot_bootstrap_root_/runtime/fingerprint/module/shell_api_stub
  $_dot_bootstrap_root_/runtime/fingerprint/module/cwd_add
  $_dot_bootstrap_root_/runtime/fingerprint/module/add_init
  $_dot_bootstrap_root_/runtime/fingerprint/module/check_last_generation_failure_status
  $_dot_bootstrap_root_/runtime/fingerprint/module/module_list
  $_dot_bootstrap_root_/runtime/fingerprint/module/hash_modules
)

for module in ${modules_arr[@]} ; do 
  source $module
  [[ -z $generation_error ]] || {
    echo "[fingerprint/init] module generation failed" | error
    echo "[fingerprint/init] at $module" | error
    echo "[fingerprint/init] due to \"$generation_error\"" | error
    break
  }
done

[[ -z "$generation_error" ]] || {
  source $_dot_bootstrap_root_/runtime/generator/hash_failure
}

if [[ -z $generation_error && ! -z $state ]] ; then
  echo "[fingerprint/init] state changes : \"$state\"" | debug
  echo "[fingerprint/init] TODO state transition : \"$state\"" | debug
fi

cp "$_log_dir_/$_session_id_" "$_dot_bootstrap_root_/generated/$_session_id_/generation_log"

if [[ -v _fingerprint_main_start ]] ; then
  local _fingerprint_main_end=$EPOCHREALTIME
  printf '[fingerprint/main] background time %.3f ms\n' "$(( (_fingerprint_main_end - _fingerprint_main_start) * 1000 ))" | debug
  unset _fingerprint_main_start 
  unset _fingerprint_main_end 
fi
