#!/bin/env zsh

echo "[fingerprint/main] entered process" | debug
if [[ -d $_dot_bootstrap_root_/cache ]] ; then
  echo "[fingerprint/main] cache exists : revalidating in background" | debug 
  source "$_dot_bootstrap_root_/runtime/fingerprint/init" &!
else 
  echo "[fingerprint/main] cache doesn't exists : generating cache" | error
  source "$_dot_bootstrap_root_/runtime/fingerprint/init" 
fi
