#!/bin/env zsh

source $_dot_bootstrap_root_/runtime/fingerprint/cwd_change
local state=""

if [[ -d $_dot_bootstrap_root_/generated ]] ; then
  local _fingerprint_main_start=$EPOCHREALTIME
  echo "[fingerprint/main] generated exists : revalidating in background" | debug 
  source "$_dot_bootstrap_root_/runtime/fingerprint/init" &!
else 
  [[ -v _fingerprint_main_start ]] && unset _fingerprint_main_start
  [[ -v SILENT_LOG ]] && {
    local _main_SILENT_LOG_status=$SILENT_LOG
    unset SILENT_LOG
  }
  echo "[fingerprint/main] generated doesn't exists : generating cache" | error
  source "$_dot_bootstrap_root_/runtime/fingerprint/init" 
  [[ -v _main_SILENT_LOG_status ]] && export SILENT_LOG=$_main_SILENT_LOG_status
fi
