#!/bin/env zsh

[[ -f "$_zforge_root_/local/public/runtime/module" ]] || {
  echo "[fingerprint/module_list] local/public/runtime/module not found generating an empty file" | warn
  touch "$_zforge_root_/local/public/runtime/module" 
  state="${state}module_list "
}

[[ -f "$_zforge_root_/cache/generated/runtime/init" ]] || {
  echo "[fingerprint/module_list] generated/init not found invoking module_list generator" | warn
  source "$_zforge_root_/runtime/generator/module_list"
  state="${state}module_list "
  return
}

grep -q "source" "$_zforge_root_/cache/generated/runtime/init" || {
  echo "[fingerprint/module_list] generated/init is empty invoking module_list generator" | warn
  source "$_zforge_root_/runtime/generator/module_list"
  state="${state}module_list "
  return
}

local activeSource="$(dirname -- $( grep "source" "$_zforge_root_/cache/generated/runtime/init" | sed -e 's/^ *source *//g' ))"

[[ -f "$activeSource/module" ]] || {
  echo "[fingerprint/module_list] generated/\$activeSource/module not found invoking module_list generator" | warn
  source "$_zforge_root_/runtime/generator/module_list"
  state="${state}module_list "
  return
}

if [[ "$( sort "$_zforge_root_/local/public/runtime/module")" == "$(awk -F ':' '{ print $2 }' "$activeSource/module" )" ]]; then
  echo "[fingerprint/module_list] local/public/runtime/module unchanged no action required" | debug
else
  echo "[fingerprint/module_list] local/public/runtime/module hash been modified invoking module_list generator" | warn
  source "$_zforge_root_/runtime/generator/module_list"
  state="${state}module_list "
fi
