#!/bin/env zsh
cp "$_dot_bootstrap_root_/runtime/share/selected_snapshot" "$_dot_bootstrap_root_/generated/selected_snapshot"
echo '#!/bin/env zsh
source "$_dot_bootstrap_root_/generated/selected_snapshot"
[[ -f "$_dot_bootstrap_root_/config/flags" ]] && {
  while read -r flag ; do
    [[ -z "$flag" ]] && continue
    eval "export $flag=1"
  done <"$_dot_bootstrap_root_/config/flags"
}
source "$_dot_bootstrap_root_/generated/$_zforge_active_snapshot_/master"
' >> "$_dot_bootstrap_root_/generated/init"
