#!/bin/env zsh

hash_digest=""

sort "$_zforge_root_/runtime/share/bootflags_generation_sensitive" | while read -r bootflag; do
  [[ -z "$bootflag" ]] && continue
  [[ -v "$bootflag" ]] && hash_digest+=$'\n'"$bootflag"
done

[[ -f "$_zforge_root_/runtime/share/dependencies" ]] && {
  hash_digest+=$'\n'"$_zforge_root_/runtime/share/dependencies:$(
    grep -v "^#.*" "$_zforge_root_/runtime/share/dependencies" | sort | awk '{ print $1 }' | sha256sum | cut -d ' ' -f1
  )"
}

find "$_zforge_root_/runtime" -type f | {
  local buff=$(cat)
  grep -Po ".+(?=IGNORE_FINGERPRINTING)" <<< "$buff" | while read -r ignored_path ; do
    local mod_buff="$( grep -vF "$ignored_path" <<< "$buff" )"
    buff="$mod_buff"
  done
  echo "$buff"
} | sort | while read -r runtime_file; do
  hash_digest+=$'\n'"$runtime_file:$( sha256sum "$runtime_file" | cut -d ' ' -f1 )"
done

count="0"

sort "$_zforge_root_/local/public/runtime/module" | while read -r module; do
  [[ -z "$module" ]] && continue
  [[ -f "$_zforge_root_/modules/$module" ]] || continue
  count=$(($count+1))
  hash_digest+=$'\n'"$count:$module:$( sha256sum "$_zforge_root_/modules/$module" | cut -d ' ' -f1 )"
done

sha256sum <<< "$hash_digest" | cut -d ' ' -f1

unset count hash_digest
