#!/bin/env zsh

[[ -f "$_dot_bootstrap_root_/generated/$_session_id_/master" ]] && rm "$_dot_bootstrap_root_/generated/$_session_id_/master"
while read -r module ; do
  local index="$( awk -F ':' '{ print $1 }' <<< "$module" )"
  if [[ -f "$_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/nomerge" ]] ; then 
    echo "[generator/generate_master_file] skipping merge for $index" | debug
    echo "source \"$_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/main\"" >> "$_dot_bootstrap_root_/generated/$_session_id_/master"
  else
    cat "$_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/main" >> "$_dot_bootstrap_root_/generated/$_session_id_/master"
  fi
done < "$_dot_bootstrap_root_/generated/$_session_id_/pmodule_priority_sorted_dependency_sorted"
state="${state}generate_master_file "
