#!/bin/env zsh
echo "$(sha256sum "$_dot_bootstrap_root_/cache/generated/runtime/$_session_id_/module" | awk '{ print $1 }'):$_session_id_" >> "$_dot_bootstrap_root_/cache/generated/runtime/failure_hash"
