#!/bin/env zsh

: > "$_zforge_root_/cache/generated/runtime/$_session_id_/flags"

while read -r flags; do
  cat "$flags" >>  "$_zforge_root_/cache/generated/runtime/$_session_id_/flags"
done < <(
  find "$_zforge_root_/cache/generated/runtime/$_session_id_/scripts" -name "flags"
)
