#!/bin/env zsh

[[ -f "$_dot_bootstrap_root_/generated/$_session_id_/flags" ]] && rm "$_dot_bootstrap_root_/generated/$_session_id_/flags"

while read -r flags; do
  cat "$flags" >>  "$_dot_bootstrap_root_/generated/$_session_id_/flags"
done < <(
  find "$_dot_bootstrap_root_/generated/$_session_id_/scripts" -name "flags"
)
