#!/bin/env zsh

[[ -d "$_zforge_root_/cache/generated/runtime/$_session_id_" ]] || mkdir -p "$_zforge_root_/cache/generated/runtime/$_session_id_"
[[ -f "$_zforge_root_/cache/generated/runtime/$_session_id_/module.temp" ]] && rm "$_zforge_root_/cache/generated/runtime/$_session_id_/module.temp"
mkdir -p "$_zforge_root_/cache/generated/runtime/$_session_id_/scripts"
touch "$_zforge_root_/cache/generated/runtime/$_session_id_/pmodule"
: > "$_zforge_root_/cache/generated/runtime/$_session_id_/module.temp"
count="0"
sort "$_zforge_root_/local/public/runtime/module" | while read -r module; do
  [[ -z "$module" ]] && continue
  [[ -f "$_zforge_root_/modules/$module" ]] || {
    echo "[generator/module_list] module '$module' listed in local/public/runtime/module but missing in modules/ : skipping" | warn
    continue
  }
  count=$(($count+1))
  echo "$count:$module:$( sha256sum "$_zforge_root_/modules/$module" | awk '{ print $1}')" >> "$_zforge_root_/cache/generated/runtime/$_session_id_/module.temp"
done
unset count
mv "$_zforge_root_/cache/generated/runtime/$_session_id_/module.temp"  "$_zforge_root_/cache/generated/runtime/$_session_id_/module"
