#!/bin/env zsh

echo "[generator/module] TODO" | error
return
[[ -d $_dot_bootstrap_root_/cache/$_session_id_ ]] || mkdir -p $_dot_bootstrap_root_/cache/$_session_id_
sort $_dot_bootstrap_root_/config/module | while read -r module; do
  echo $module
done


