#!/bin/env zsh

[[ -d "$_dot_bootstrap_root_/generated/$_session_id_/scripts" ]] || mkdir -p "$_dot_bootstrap_root_/generated/$_session_id_/scripts"

echo "[generator/module] generation required for module $module" | debug
