#!/bin/env zsh 

echo "$_session_id_:$( source "$_zforge_root_/runtime/generator/config_module_hash" )" >> "$_zforge_root_/cache/generated/runtime/snapshots"
state="${state}publish_latest_snapshot_state "
