#!/bin/env zsh 

echo "$_session_id_:$(sha256sum "$_dot_bootstrap_root_/generated/$_session_id_/module" | awk '{ print $1 }')" >> "$_dot_bootstrap_root_/generated/snapshots"
state="${state}publish_latest_snapshot_state "
