#!/bin/env zsh 

sha256sum "$_dot_bootstrap_root_/generated/$_session_id_/module" | awk '{ print $1 }' > "$_dot_bootstrap_root_/generated/last_generation"
echo "$_session_id_" | awk '{ print $1 }' >> "$_dot_bootstrap_root_/generated/last_generation"
state="${state}publish_latest_snapshot_state "
