#!/bin/env zsh

[[ -f "$_zforge_root_/cache/generated/runtime/snapshots_$_session_id_" ]] && rm "$_zforge_root_/cache/generated/runtime/snapshots_$_session_id_"
awk "!/^$snapshot_entry/" "$_zforge_root_/cache/generated/runtime/snapshots" >> "$_zforge_root_/cache/generated/runtime/snapshots_$_session_id_"
echo "$snapshot_entry" >> "$_zforge_root_/cache/generated/runtime/snapshots_$_session_id_"
mv "$_zforge_root_/cache/generated/runtime/snapshots_$_session_id_" "$_zforge_root_/cache/generated/runtime/snapshots"
