#!/bin/env zsh

[[ -d "$_dot_bootstrap_root_/cache/generated/runtime/" ]] || mkdir "$_dot_bootstrap_root_/cache/generated/runtime"
[[ -f "$_dot_bootstrap_root_/cache/generated/runtime/shell_api_stub_temp" ]] && rm "$_dot_bootstrap_root_/cache/generated/runtime/shell_api_stub_temp"

echo "# $livehash" > "$_dot_bootstrap_root_/cache/generated/runtime/shell_api_stub_$_session_id_"

for file in "$_dot_bootstrap_root_/runtime/shell_api/"* ; do
  [[ "$file" == "$_dot_bootstrap_root_/runtime/shell_api/IGNORE_FINGERPRINTING" ]] && continue
  "$_dot_bootstrap_root_/runtime/generator/helper/lazyWrapperGenerator" "$file" >> "$_dot_bootstrap_root_/cache/generated/runtime/shell_api_stub_$_session_id_"
done

mv "$_dot_bootstrap_root_/cache/generated/runtime/shell_api_stub_$_session_id_" "$_dot_bootstrap_root_/cache/generated/runtime/shell_api_stub"
