#!/bin/env zsh

typeset -A indexToWhole
typeset -A nameToIndex
typeset -A printed

# create dict
while read -r module ; do
  index="$( awk -F ':' '{ print $1 }' <<< "$module")"
  indexToWhole["$index"]="$module"
done <"$_dot_bootstrap_root_/generated/$_session_id_/pmodule_priority_sorted"

while read -r module ; do
  index="$( awk -F ':' '{ print $1 }' <<< "$module")"
  name="$( awk -F ':' '{ print $2 }' <<< "$module")"
  nameToIndex["$name"]="$index"
done <"$_dot_bootstrap_root_/generated/$_session_id_/module"

priortisedDependencies() {
  while read -r dependency ; do 
    local index="${nameToIndex["$dependency"]}"
    echo "${indexToWhole["$index"]}"
  done < "$1"
}

sortedDependencies() {
  local buffer="$(cat)"
  grep -E '.+:-[0-9]+$' <<< "$buffer" | sort -t: -k2,2n ;
  grep -E '.+:\?$' <<< "$buffer" ;
  grep -E '.+:[0-9]+$' <<< "$buffer" | sort -t: -k2,2n 
}

processDependency() {
  local module="$1"
  local index="$( awk -F ':' '{ print $1 }' <<< "$module" )"
  [[ -z "${printed["$index"]}" ]] || return
  [[ -f "$_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/dependencies" ]] && {
    while read -r dependency; do
      processDependency "$dependency"
    done < <(priortisedDependencies "$_dot_bootstrap_root_/generated/$_session_id_/scripts/$index/dependencies" | sortedDependencies)
  }
  printed["$index"]=1
  echo "$module"
}

(while read -r module ; do
  processDependency "$module"
done <"$_dot_bootstrap_root_/generated/$_session_id_/pmodule_priority_sorted") > "$_dot_bootstrap_root_/generated/$_session_id_/pmodule_priority_sorted_dependency_sorted"

unset indexToWhole nameToIndex printed priortisedDependencies sortedDependencies processDependency 
state="${state}sort_dependencies "
