#!/bin/env zsh

_load_shell_api_start=$EPOCHREALTIME

if [[ -f "$_zforge_root_/cache/generated/runtime/shell_api_stub" ]] ; then
  source "$_zforge_root_/cache/generated/runtime/shell_api_stub"
else
  echo "[loaders/load_shell_api] shell_api_stub not found doing looped loading" | debug
  for file in "$_zforge_root_/runtime/shell_api/"* ; do
    [[ "$file" == "$_zforge_root_/runtime/shell_api/IGNORE_FINGERPRINTING" ]] && continue
    source "$file"
  done
fi

_load_shell_api_end=$EPOCHREALTIME

printf '[load_shell_api] %.3f ms\n' "$(( (_load_shell_api_end - _load_shell_api_start) * 1000 ))" | debug
