#!/bin/env zsh
#  

zmodload zsh/datetime
start=$EPOCHREALTIME

for file in $_dot_bootstrap_root_/runtime/commands/*; do
  source $file
done

end=$EPOCHREALTIME

printf 'sourcing commands %.3f ms\n' "$(( (end - start) * 1000 ))" | debug
