#!/bin/env zsh

local state=""

if [[ -f "$_zforge_root_/cache/generated/runtime/snapshots" ]] && (( "${#$(cat "$_zforge_root_/cache/generated/runtime/snapshots" | tr '\n' ' ' | sed 's/ //g')}" )) && [[ ! -v _ZFORGE_FORCE_FOREGROUND_GENERATION ]] ; then
  [[ -v "FREEZE_BACKGROUND_VALIDATION" ]] && {
    echo  "[orchestrator/main] BACKGROUND VALIDATION IS FROZEN" | debug
    echo  "[orchestrator/main] disable flag FREEZE_BACKGROUND_VALIDATION for background validation" | debug
    return
  }
  local _orchestrator_main_start=$EPOCHREALTIME
  echo "[orchestrator/main] generated exists : revalidating in background" | debug 
  source "$_zforge_root_/runtime/orchestrator/init" 2>&1 | {
    local buff="$(cat)";
    [[ -n "$buff" ]] && {
      echo "[orchestrator/main] [background generation output leaks]" | debug
      print -- "[orchestrator/main] $buff"                            | debug
    }
  } &!
else
  [[ -v _orchestrator_main_start ]] && unset _orchestrator_main_start
  [[ -v LOGALL ]] || {
    local _main_LOGALL_status=$SILENT_LOG
    export LOGALL=1
  }
  [[ -v SILENT_LOG ]] && {
    local _main_SILENT_LOG_status=$SILENT_LOG
    unset SILENT_LOG
  }
  if [[ -v _ZFORGE_FORCE_FOREGROUND_GENERATION ]] ; then
    echo "[orchestrator/main] generating new snapshot" | debug
  else
    echo "[orchestrator/main] generated doesn't exists : generating cache" | error
  fi
  source "$_zforge_root_/runtime/orchestrator/init" 
  [[ -v _main_SILENT_LOG_status ]] && export SILENT_LOG=$_main_SILENT_LOG_status
  [[ -v _main_LOGALL_status ]] && unset LOGALL
  [[ -v _ZFORGE_FORCE_FOREGROUND_GENERATION ]] && unset _ZFORGE_FORCE_FOREGROUND_GENERATION
fi
