set-option -g default-shell /usr/bin/zsh
# set -g mouse on
set -g prefix C-x
unbind-key C-b
set -g default-terminal "tmux-256color"
set-window-option -g mode-keys vi

# for nvim image support
set -gq allow-passthrough on
set -g visual-activity off

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

# act like vim
setw -g mode-keys vi
set -g @plugin 'christoomey/vim-tmux-navigator'
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key V split-window -v 
bind-key v split-window -h

# resize panes
bind-key -r H resize-pane -L 5
bind-key -r L resize-pane -R 5
bind-key -r K resize-pane -U 3
bind-key -r J resize-pane -D 3

# shortcuts
bind-key a new-window 
#bind-key k kill-window
#command-alias -A q kill-window
#bind q kill-window
bind-key m split-window -h -l 20% \; \
  split-window -v -l 60% \; \
  send-keys 'cmatrix -s && exit' Enter \; \
  select-pane -U \; \
  send-keys 'fetch --infinite --no-info && exit' Enter \; \
  select-pane -L

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'

#set -g @plugin 'dracula/tmux'
##set -g @plugin 'bjesus/muxile'
#
## dracula conf
#set -g @dracula-show-powerline true
## set -g @dracula-fixed-location "YOUR-NAME"
#set -g @dracula-plugins "weather"
#set -g @dracula-show-flags true 
#set -g @dracula-show-left-icon session
set -g status-position top
#set -g @dracula-transparent-powerline-bg true
## the left separator symbol is inversed with a transparent background, you can modify it with any symbol you like
#set -g @dracula-inverse-divider 

# to install the packages run leader+I
# the I is capital
# initialize TMUX plugin manager ( keep this line at the very bottom of the tmux.conf )
set -g @themepack 'powerline/double/cyan'

run '~/.tmux/plugins/tpm/tpm'
