#!/bin/env zsh

[[ $ZSH_EVAL_CONTEXT != *:file* ]] || { echo "Don't source this file" ; return 1}
(( $# == 1 )) || { echo "Pass a file name"; exit 1; }
[[ -f $1 ]] || { echo "File not found"; exit 1; }

rp=$(realpath "$1")

echo 1
#if zsh -c "source ${(q)rp} >/dev/null 2>&1"; then
#  echo 1
#else
#  echo 0
#fi
