#!/bin/env zsh

(( $# == 1 )) || { echo "Pass a file name"; exit 1; }
[[ -f $1 ]] || { echo "File not found"; exit 1; }

priority_present="$(grep -E '^[[:space:]]*#[[:space:]]*@p[[:space:]]*->[[:space:]]*[^[:space:]]+' $1 |
  sed -E 's/^[[:space:]]*#[[:space:]]*@p[[:space:]]*->[[:space:]]*//g' )"

(( "$( echo $priority_present | wc -l )" != 1 )) && {
  generation_error="[generator/helper/extract_priority] module $name : more then one priority_present '$priority_present'"
  echo "[generator/helper/extract_priority] module $name : more then one priority_present '$priority_present'" | error
  echo "!"
  if [[ $ZSH_EVAL_CONTEXT == *:file* ]] ; then
    return 
  else 
    exit
  fi
}

echo "$priority_present"
