#!/bin/env zsh

[[ $ZSH_EVAL_CONTEXT != *:file* ]] || { echo "Don't source this file" ; return 1}
(( $# == 1 )) || { echo "Pass a file name"; exit 1; }
[[ -f $1 ]] || { echo "File not found"; exit 1; }

rp=$(realpath "$1")
rp=${rp/#"$_dot_bootstrap_root_"/\$_dot_bootstrap_root_}
rp=${rp/#"$HOME"/\$HOME}

zmodload zsh/datetime

unfunc_random="_unfunc_$EPOCHREALTIME"

funcs="$(grep -E '^[[:space:]]*[^ #]+[[:space:]]*\([[:space:]]*\)[[:space:]]*\{' "$1" |
  sed -E 's/[[:space:]]*\([[:space:]]*\)[[:space:]]*\{.*//')"

unfunc="$unfunc_random() { $( echo $funcs | sed -e 's/\(.*\)/unfunction \1;/' | tr '\n' ' ' ) source \"$rp\" }"

echo $unfunc

while IFS= read -r function; do
  print -r -- "$function(){ $unfunc_random ; $function \"\$@\"; }"
done < <( echo $funcs )
