#!/bin/env zsh

[[ -d "$_dot_bootstrap_root_/cache" ]] && return

chmod -R +x "$_dot_bootstrap_root_/runtime"
mkdir -p "$_dot_bootstrap_root_/cache/generated/zforge"
mkdir -p "$_dot_bootstrap_root_/local/public/config"
mkdir -p "$_dot_bootstrap_root_/local/private/config"
mkdir -p "$_dot_bootstrap_root_/local/public/static_config"
mkdir -p "$_dot_bootstrap_root_/local/private/static_config"
